version: '3.8'

services:
    app:
        build: .
        container_name: cloudcart_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        depends_on:
            - db
        networks:
            - cloudcart_network
        environment:
            - DB_CONNECTION=pgsql
            - DB_HOST=cloudcart_db
            - DB_PORT=5432
            - DB_DATABASE=cloudcart
            - DB_USERNAME=postgres
            - DB_PASSWORD=postgres
        ports:
            - "8000:8000"

    db:
        image: postgres:15
        container_name: cloudcart_db
        restart: unless-stopped
        environment:
            POSTGRES_DB: cloudcart
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "5432:5432"
        volumes:
            - pg_data:/var/lib/postgresql/data
        networks:
            - cloudcart_network
    phpmyadmin:
        image: dpage/pgadmin4
        container_name: cloudcart_pgadmin
        restart: unless-stopped
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - "5050:80"
        depends_on:
            - db
        networks:
            - cloudcart_network

networks:
    cloudcart_network:

volumes:
    pg_data:
